sudo: enabled

language: cpp

# safelist
branches:
  only:
  - master

before_install:
  - ls
  - pwd
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-7 -y
  - export CXX=g++-7
  - wget https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.tar.gz -O /tmp/cmake.tar.gz
  - tar -xzf /tmp/cmake.tar.gz
  - export PATH=$PATH:$PWD/cmake-3.12.2-Linux-x86_64/bin/
  - cmake-3.12.2-Linux-x86_64/bin/cmake --version
  - git clone https://github.com/Microsoft/vcpkg.git
  - ./vcpkg/bootstrap-vcpkg.sh
  - touch vcpkg/triplets/x64-linux-cxx14.cmake
  - echo "set(VCPKG_TARGET_ARCHITECTURE x64)" >> vcpkg/triplets/x64-linux-cxx14.cmake
  - echo "set(VCPKG_LIBRARY_LINKAGE static)" >> vcpkg/triplets/x64-linux-cxx14.cmake
  - echo "set(VCPKG_CMAKE_SYSTEM_NAME Linux)" >> vcpkg/triplets/x64-linux-cxx14.cmake
  - echo "set(VCPKG_CRT_LINKAGE dynamic)" >> vcpkg/triplets/x64-linux-cxx14.cmake
  - echo "set(VCPKG_CXX_FLAGS \"-std=c++14\")" >> vcpkg/triplets/x64-linux-cxx14.cmake
  - echo "set(VCPKG_C_FLAGS \"\")" >> vcpkg/triplets/x64-linux-cxx14.cmake
  - cd vcpkg
  - ./vcpkg install boost-asio:x64-linux-cxx14
  - ./vcpkg install boost-beast:x64-linux-cxx14
  - ./vcpkg install catch2:x64-linux-cxx14
  - cd ..

install:
  - mkdir build_debug
  - cd build_debug
  - ../cmake-3.12.2-Linux-x86_64/bin/cmake -DCMAKE_TOOLCHAIN_FILE=../foxy-travis.cmake ..
  - ../cmake-3.12.2-Linux-x86_64/bin/cmake --build . --target all -- -j4

script:
  - ctest .

notifications:
  email:
    false
